version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: messenger-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: